import { Kitchen, MenuItem } from './types';

export const MOCK_KITCHENS: Kitchen[] = [
  {
    id: 'kitchen-1',
    name: 'Ghar Ka Khana',
    description: 'Authentic home-cooked North Indian meals made with love. Dals, curries, fresh rotis daily.',
    cuisine: 'Indian',
    type: 'tiffin',
    address: '234 Robson St',
    city: 'Vancouver',
    rating: 4.9,
    reviewCount: 183,
    isOpen: true,
    isHalal: true,
    isVeg: false,
    deliveryTime: '25–35 min',
    pricePerMeal: 9,
  },
  {
    id: 'kitchen-2',
    name: 'Nourish Box',
    description: 'Clean, macro-balanced meals for health-conscious eaters. High protein, low carb options daily.',
    cuisine: 'Healthy',
    type: 'tiffin',
    address: '89 Commercial Dr',
    city: 'Vancouver',
    rating: 4.7,
    reviewCount: 142,
    isOpen: true,
    isHalal: false,
    isVeg: true,
    deliveryTime: '20–30 min',
    pricePerMeal: 11,
  },
  {
    id: 'kitchen-3',
    name: 'Chabar Kitchen',
    description: 'Our own restaurant chain. Fresh, bold flavours — from biryanis to wraps.',
    cuisine: 'Indian',
    type: 'restaurant',
    address: '512 Granville St',
    city: 'Vancouver',
    rating: 4.6,
    reviewCount: 312,
    isOpen: true,
    isHalal: true,
    isVeg: false,
    deliveryTime: '20–35 min',
    pricePerMeal: 13,
  },
  {
    id: 'kitchen-4',
    name: 'Desi Dhaba',
    description: 'Punjab-style home cooking. Sarson da saag, makki roti, authentic tadkas.',
    cuisine: 'Punjabi',
    type: 'tiffin',
    address: '14 Fraser St',
    city: 'Vancouver',
    rating: 4.8,
    reviewCount: 97,
    isOpen: false,
    isHalal: true,
    isVeg: false,
    deliveryTime: '30–40 min',
    pricePerMeal: 8,
  },
  {
    id: 'kitchen-5',
    name: 'Green Bowl Co.',
    description: 'Plant-based South Asian bowls. Lentils, greens, spices — all vegan.',
    cuisine: 'Vegan',
    type: 'tiffin',
    address: '78 Main St',
    city: 'Vancouver',
    rating: 4.5,
    reviewCount: 64,
    isOpen: true,
    isHalal: false,
    isVeg: true,
    deliveryTime: '25–35 min',
    pricePerMeal: 10,
  },
  {
    id: 'kitchen-6',
    name: 'Biryani Bros',
    description: 'One focus: the best biryani in Vancouver. Chicken, lamb, veg — slow-cooked daily.',
    cuisine: 'Pakistani',
    type: 'restaurant',
    address: '209 Kingsway',
    city: 'Vancouver',
    rating: 4.9,
    reviewCount: 256,
    isOpen: true,
    isHalal: true,
    isVeg: false,
    deliveryTime: '30–45 min',
    pricePerMeal: 14,
  },
];

export const MOCK_MENU_ITEMS: Record<string, MenuItem[]> = {
  'kitchen-1': [
    { id: 'm1', kitchenId: 'kitchen-1', name: 'Dal makhani + rice', description: 'Slow-cooked black lentils, basmati rice, green salad', price: 9, calories: 520, protein: 22, isAvailable: true, tags: ['Halal', 'Vegetarian'] },
    { id: 'm2', kitchenId: 'kitchen-1', name: 'Paneer paratha set', description: '3 parathas, yogurt, pickle, masala chai', price: 10, calories: 680, protein: 28, isAvailable: true, tags: ['Vegetarian'] },
    { id: 'm3', kitchenId: 'kitchen-1', name: 'Chole bhature', description: 'Spiced chickpeas, 2 fluffy bhaturas, onion salad', price: 11, calories: 740, protein: 24, isAvailable: true, tags: ['Halal', 'Vegetarian'] },
    { id: 'm4', kitchenId: 'kitchen-1', name: 'Chicken tikka + rice', description: 'Tandoor-marinated chicken, jeera rice, raita', price: 12, calories: 620, protein: 38, isAvailable: true, tags: ['Halal', 'High protein'] },
    { id: 'm5', kitchenId: 'kitchen-1', name: 'Lamb keema + roti', description: 'Minced lamb curry, 3 fresh rotis, onion salad', price: 13, calories: 660, protein: 41, isAvailable: true, tags: ['Halal', 'High protein'] },
    { id: 'm6', kitchenId: 'kitchen-1', name: 'Paneer bhurji + quinoa', description: 'Scrambled cottage cheese, quinoa, cucumber raita', price: 11, calories: 580, protein: 32, isAvailable: true, tags: ['Vegetarian', 'High protein'] },
  ],
  'kitchen-2': [
    { id: 'm7', kitchenId: 'kitchen-2', name: 'Grilled chicken bowl', description: 'Grilled chicken breast, quinoa, roasted veg, tahini', price: 13, calories: 490, protein: 44, isAvailable: true, tags: ['High protein', 'Low carb'] },
    { id: 'm8', kitchenId: 'kitchen-2', name: 'Lentil power bowl', description: 'Red lentils, brown rice, kale, lemon dressing', price: 11, calories: 520, protein: 26, isAvailable: true, tags: ['Vegan', 'High protein'] },
    { id: 'm9', kitchenId: 'kitchen-2', name: 'Egg bhurji wrap', description: '3 scrambled eggs, whole wheat wrap, sriracha', price: 10, calories: 430, protein: 30, isAvailable: true, tags: ['Vegetarian', 'High protein'] },
  ],
  'kitchen-3': [
    { id: 'm10', kitchenId: 'kitchen-3', name: 'Chicken biryani', description: 'Dum-cooked basmati, tender chicken, saffron, raita', price: 16, calories: 720, protein: 38, isAvailable: true, tags: ['Halal'] },
    { id: 'm11', kitchenId: 'kitchen-3', name: 'Seekh kebab platter', description: '4 seekh kebabs, naan, mint chutney, onion salad', price: 18, calories: 640, protein: 46, isAvailable: true, tags: ['Halal', 'High protein'] },
    { id: 'm12', kitchenId: 'kitchen-3', name: 'Veg thali', description: 'Dal, paneer sabzi, rice, 2 rotis, salad, dessert', price: 14, calories: 780, protein: 26, isAvailable: true, tags: ['Vegetarian'] },
  ],
};

export const CATEGORIES = ['All', 'Tiffin plans', 'Healthy', 'Indian', 'Halal', 'Vegetarian', 'Vegan'];

export const DELIVERY_DAYS = [
  { day: 'Mon', time: '12–1pm' },
  { day: 'Tue', time: '12–1pm' },
  { day: 'Wed', time: '12–1pm' },
  { day: 'Thu', time: '6–7pm' },
  { day: 'Fri', time: '6–7pm' },
  { day: 'Sat', time: '11–12pm' },
  { day: 'Sun', time: '11–12pm' },
];
